export interface Contrato {
    id: number | undefined;
    nombreComprador: string | undefined;
    nombreVendedor: string | undefined;
    vendedorAddress: string | undefined;
    compradorAddress: string | undefined;
    intermediarioAddress: string | undefined;
    emailVendedor: string | undefined;
    telefonoVendedor: string | undefined;
    incoterm: string | undefined;
    fleteACargoDe: string | undefined;
    puntoControlCalidad: string | undefined;
    cantidadToneladas: number | undefined;
    precioPorTonelada: number | undefined;
    tipoContrato: string | undefined;
    fechaEntrega: string | undefined;
    lugarEntrega: string | undefined;
    condicionesCalidad: string | undefined;
    modalidadPago: string | undefined;
    accionIncumplimiento: string | undefined;
}