/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ContratoGranosSoja {
      
    export type PartesStruct = {comprador: AddressLike, nroIdentidadComprador: string, nombreComprador: string, vendedor: AddressLike, nroIdentidadVendedor: string, nombreVendedor: string, broker: AddressLike, nroIdentidadBroker: string, nombreBroker: string}

    export type PartesStructOutput = [comprador: string, nroIdentidadComprador: string, nombreComprador: string, vendedor: string, nroIdentidadVendedor: string, nombreVendedor: string, broker: string, nroIdentidadBroker: string, nombreBroker: string] & {comprador: string, nroIdentidadComprador: string, nombreComprador: string, vendedor: string, nroIdentidadVendedor: string, nombreVendedor: string, broker: string, nroIdentidadBroker: string, nombreBroker: string }
  

    export type CondicionesGranoStruct = {cantidadToneladasMetricas: BigNumberish, tipoGrano: string, cosecha: string}

    export type CondicionesGranoStructOutput = [cantidadToneladasMetricas: bigint, tipoGrano: string, cosecha: string] & {cantidadToneladasMetricas: bigint, tipoGrano: string, cosecha: string }
  

    export type CondicionesEntregaStruct = {empaque: string, fechaEntregaInicio: BigNumberish, fechaEntregaFin: BigNumberish}

    export type CondicionesEntregaStructOutput = [empaque: string, fechaEntregaInicio: bigint, fechaEntregaFin: bigint] & {empaque: string, fechaEntregaInicio: bigint, fechaEntregaFin: bigint }
  

    export type CondicionesPrecioStruct = {tipoContrato: BigNumberish, precioPorToneladaMetrica: BigNumberish, precioCBOTBushel: BigNumberish, ajusteCBOT: BigNumberish, fechaPrecioChicago: BigNumberish, incoterm: string, precioFinal: BigNumberish}

    export type CondicionesPrecioStructOutput = [tipoContrato: bigint, precioPorToneladaMetrica: bigint, precioCBOTBushel: bigint, ajusteCBOT: bigint, fechaPrecioChicago: bigint, incoterm: string, precioFinal: bigint] & {tipoContrato: bigint, precioPorToneladaMetrica: bigint, precioCBOTBushel: bigint, ajusteCBOT: bigint, fechaPrecioChicago: bigint, incoterm: string, precioFinal: bigint }
  

    export type CondicionesEmbarqueStruct = {puertoEmbarque: string, destinoFinal: string}

    export type CondicionesEmbarqueStructOutput = [puertoEmbarque: string, destinoFinal: string] & {puertoEmbarque: string, destinoFinal: string }
  

    export type ContratoStruct = {partes: ContratoGranosSoja.PartesStruct, condicionesGrano: ContratoGranosSoja.CondicionesGranoStruct, condicionesEntrega: ContratoGranosSoja.CondicionesEntregaStruct, condicionesPrecio: ContratoGranosSoja.CondicionesPrecioStruct, condicionesEmbarque: ContratoGranosSoja.CondicionesEmbarqueStruct, hashVersionContrato: string, evidenceURI: string, fechaCelebracionContrato: BigNumberish, estado: BigNumberish}

    export type ContratoStructOutput = [partes: ContratoGranosSoja.PartesStructOutput, condicionesGrano: ContratoGranosSoja.CondicionesGranoStructOutput, condicionesEntrega: ContratoGranosSoja.CondicionesEntregaStructOutput, condicionesPrecio: ContratoGranosSoja.CondicionesPrecioStructOutput, condicionesEmbarque: ContratoGranosSoja.CondicionesEmbarqueStructOutput, hashVersionContrato: string, evidenceURI: string, fechaCelebracionContrato: bigint, estado: bigint] & {partes: ContratoGranosSoja.PartesStructOutput, condicionesGrano: ContratoGranosSoja.CondicionesGranoStructOutput, condicionesEntrega: ContratoGranosSoja.CondicionesEntregaStructOutput, condicionesPrecio: ContratoGranosSoja.CondicionesPrecioStructOutput, condicionesEmbarque: ContratoGranosSoja.CondicionesEmbarqueStructOutput, hashVersionContrato: string, evidenceURI: string, fechaCelebracionContrato: bigint, estado: bigint }
  
    }

  export interface ContratoGranosSojaInterface extends Interface {
    getFunction(nameOrSignature: "approve" | "balanceOf" | "cancelarContrato" | "confirmarEntregaMetaTx" | "contadorContratos" | "contratos" | "crearContrato" | "editarContrato" | "enviarContrato" | "firmarContratoMetaTx" | "getApproved" | "isApprovedForAll" | "isTrustedForwarder" | "name" | "obtenerContratos" | "owner" | "ownerOf" | "relayer" | "renounceOwnership" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "setApprovalForAll" | "setRelayer" | "supportsInterface" | "symbol" | "tokenURI" | "transferFrom" | "transferOwnership" | "trustedForwarder"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "ApprovalForAll" | "ContratoCancelado" | "ContratoCelebrado" | "ContratoCerrado" | "ContratoCreado" | "ContratoEditado" | "ContratoFirmado" | "EntregaConfirmada" | "OwnershipTransferred" | "PrecioFijado" | "RelayerActualizado" | "Transfer"): EventFragment;

    encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'cancelarContrato', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'confirmarEntregaMetaTx', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contadorContratos', values?: undefined): string;
encodeFunctionData(functionFragment: 'contratos', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'crearContrato', values: [ContratoGranosSoja.ContratoStruct]): string;
encodeFunctionData(functionFragment: 'editarContrato', values: [BigNumberish, ContratoGranosSoja.ContratoStruct]): string;
encodeFunctionData(functionFragment: 'enviarContrato', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'firmarContratoMetaTx', values: [BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isTrustedForwarder', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'obtenerContratos', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'relayer', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setRelayer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'trustedForwarder', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelarContrato', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmarEntregaMetaTx', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contadorContratos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contratos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'crearContrato', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'editarContrato', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enviarContrato', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'firmarContratoMetaTx', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTrustedForwarder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'obtenerContratos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'relayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRelayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trustedForwarder', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContratoCanceladoEvent {
      export type InputTuple = [idContrato: BigNumberish, ejecutor: AddressLike, motivo: string, fechaCancelacion: BigNumberish];
      export type OutputTuple = [idContrato: bigint, ejecutor: string, motivo: string, fechaCancelacion: bigint];
      export interface OutputObject {idContrato: bigint, ejecutor: string, motivo: string, fechaCancelacion: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContratoCelebradoEvent {
      export type InputTuple = [idContrato: BigNumberish, fechaCelebracion: BigNumberish];
      export type OutputTuple = [idContrato: bigint, fechaCelebracion: bigint];
      export interface OutputObject {idContrato: bigint, fechaCelebracion: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContratoCerradoEvent {
      export type InputTuple = [idContrato: BigNumberish, nuevoEstado: BigNumberish];
      export type OutputTuple = [idContrato: bigint, nuevoEstado: bigint];
      export interface OutputObject {idContrato: bigint, nuevoEstado: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContratoCreadoEvent {
      export type InputTuple = [idContrato: BigNumberish, comprador: AddressLike, vendedor: AddressLike];
      export type OutputTuple = [idContrato: bigint, comprador: string, vendedor: string];
      export interface OutputObject {idContrato: bigint, comprador: string, vendedor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContratoEditadoEvent {
      export type InputTuple = [idContrato: BigNumberish, comprador: AddressLike];
      export type OutputTuple = [idContrato: bigint, comprador: string];
      export interface OutputObject {idContrato: bigint, comprador: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContratoFirmadoEvent {
      export type InputTuple = [idContrato: BigNumberish, vendedor: AddressLike, consentHash: string, evidenceURI: string];
      export type OutputTuple = [idContrato: bigint, vendedor: string, consentHash: string, evidenceURI: string];
      export interface OutputObject {idContrato: bigint, vendedor: string, consentHash: string, evidenceURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EntregaConfirmadaEvent {
      export type InputTuple = [idContrato: BigNumberish, vendedor: AddressLike];
      export type OutputTuple = [idContrato: bigint, vendedor: string];
      export interface OutputObject {idContrato: bigint, vendedor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PrecioFijadoEvent {
      export type InputTuple = [idContrato: BigNumberish, precioFinal: BigNumberish];
      export type OutputTuple = [idContrato: bigint, precioFinal: bigint];
      export interface OutputObject {idContrato: bigint, precioFinal: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RelayerActualizadoEvent {
      export type InputTuple = [oldRelayer: AddressLike, newRelayer: AddressLike];
      export type OutputTuple = [oldRelayer: string, newRelayer: string];
      export interface OutputObject {oldRelayer: string, newRelayer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ContratoGranosSoja extends BaseContract {
    
    connect(runner?: ContractRunner | null): ContratoGranosSoja;
    waitForDeployment(): Promise<this>;

    interface: ContratoGranosSojaInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    cancelarContrato: TypedContractMethod<
      [id: BigNumberish, motivo: string, ],
      [void],
      'nonpayable'
    >
    

    
    confirmarEntregaMetaTx: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    contadorContratos: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    contratos: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[ContratoGranosSoja.PartesStructOutput, ContratoGranosSoja.CondicionesGranoStructOutput, ContratoGranosSoja.CondicionesEntregaStructOutput, ContratoGranosSoja.CondicionesPrecioStructOutput, ContratoGranosSoja.CondicionesEmbarqueStructOutput, string, string, bigint, bigint] & {partes: ContratoGranosSoja.PartesStructOutput, condicionesGrano: ContratoGranosSoja.CondicionesGranoStructOutput, condicionesEntrega: ContratoGranosSoja.CondicionesEntregaStructOutput, condicionesPrecio: ContratoGranosSoja.CondicionesPrecioStructOutput, condicionesEmbarque: ContratoGranosSoja.CondicionesEmbarqueStructOutput, hashVersionContrato: string, evidenceURI: string, fechaCelebracionContrato: bigint, estado: bigint }],
      'view'
    >
    

    
    crearContrato: TypedContractMethod<
      [datos: ContratoGranosSoja.ContratoStruct, ],
      [void],
      'nonpayable'
    >
    

    
    editarContrato: TypedContractMethod<
      [id: BigNumberish, nuevosDatos: ContratoGranosSoja.ContratoStruct, ],
      [void],
      'nonpayable'
    >
    

    
    enviarContrato: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    firmarContratoMetaTx: TypedContractMethod<
      [id: BigNumberish, consentHash: string, evidenceURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isTrustedForwarder: TypedContractMethod<
      [forwarder: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    obtenerContratos: TypedContractMethod<
      [],
      [ContratoGranosSoja.ContratoStructOutput[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    relayer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setRelayer: TypedContractMethod<
      [_relayer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    trustedForwarder: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelarContrato'): TypedContractMethod<
      [id: BigNumberish, motivo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmarEntregaMetaTx'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contadorContratos'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'contratos'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[ContratoGranosSoja.PartesStructOutput, ContratoGranosSoja.CondicionesGranoStructOutput, ContratoGranosSoja.CondicionesEntregaStructOutput, ContratoGranosSoja.CondicionesPrecioStructOutput, ContratoGranosSoja.CondicionesEmbarqueStructOutput, string, string, bigint, bigint] & {partes: ContratoGranosSoja.PartesStructOutput, condicionesGrano: ContratoGranosSoja.CondicionesGranoStructOutput, condicionesEntrega: ContratoGranosSoja.CondicionesEntregaStructOutput, condicionesPrecio: ContratoGranosSoja.CondicionesPrecioStructOutput, condicionesEmbarque: ContratoGranosSoja.CondicionesEmbarqueStructOutput, hashVersionContrato: string, evidenceURI: string, fechaCelebracionContrato: bigint, estado: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'crearContrato'): TypedContractMethod<
      [datos: ContratoGranosSoja.ContratoStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'editarContrato'): TypedContractMethod<
      [id: BigNumberish, nuevosDatos: ContratoGranosSoja.ContratoStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'enviarContrato'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'firmarContratoMetaTx'): TypedContractMethod<
      [id: BigNumberish, consentHash: string, evidenceURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isTrustedForwarder'): TypedContractMethod<
      [forwarder: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'obtenerContratos'): TypedContractMethod<
      [],
      [ContratoGranosSoja.ContratoStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'relayer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRelayer'): TypedContractMethod<
      [_relayer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'trustedForwarder'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'ContratoCancelado'): TypedContractEvent<ContratoCanceladoEvent.InputTuple, ContratoCanceladoEvent.OutputTuple, ContratoCanceladoEvent.OutputObject>;
getEvent(key: 'ContratoCelebrado'): TypedContractEvent<ContratoCelebradoEvent.InputTuple, ContratoCelebradoEvent.OutputTuple, ContratoCelebradoEvent.OutputObject>;
getEvent(key: 'ContratoCerrado'): TypedContractEvent<ContratoCerradoEvent.InputTuple, ContratoCerradoEvent.OutputTuple, ContratoCerradoEvent.OutputObject>;
getEvent(key: 'ContratoCreado'): TypedContractEvent<ContratoCreadoEvent.InputTuple, ContratoCreadoEvent.OutputTuple, ContratoCreadoEvent.OutputObject>;
getEvent(key: 'ContratoEditado'): TypedContractEvent<ContratoEditadoEvent.InputTuple, ContratoEditadoEvent.OutputTuple, ContratoEditadoEvent.OutputObject>;
getEvent(key: 'ContratoFirmado'): TypedContractEvent<ContratoFirmadoEvent.InputTuple, ContratoFirmadoEvent.OutputTuple, ContratoFirmadoEvent.OutputObject>;
getEvent(key: 'EntregaConfirmada'): TypedContractEvent<EntregaConfirmadaEvent.InputTuple, EntregaConfirmadaEvent.OutputTuple, EntregaConfirmadaEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PrecioFijado'): TypedContractEvent<PrecioFijadoEvent.InputTuple, PrecioFijadoEvent.OutputTuple, PrecioFijadoEvent.OutputObject>;
getEvent(key: 'RelayerActualizado'): TypedContractEvent<RelayerActualizadoEvent.InputTuple, RelayerActualizadoEvent.OutputTuple, RelayerActualizadoEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'ContratoCancelado(uint256,address,string,uint256)': TypedContractEvent<ContratoCanceladoEvent.InputTuple, ContratoCanceladoEvent.OutputTuple, ContratoCanceladoEvent.OutputObject>;
      ContratoCancelado: TypedContractEvent<ContratoCanceladoEvent.InputTuple, ContratoCanceladoEvent.OutputTuple, ContratoCanceladoEvent.OutputObject>;
    

      'ContratoCelebrado(uint256,uint256)': TypedContractEvent<ContratoCelebradoEvent.InputTuple, ContratoCelebradoEvent.OutputTuple, ContratoCelebradoEvent.OutputObject>;
      ContratoCelebrado: TypedContractEvent<ContratoCelebradoEvent.InputTuple, ContratoCelebradoEvent.OutputTuple, ContratoCelebradoEvent.OutputObject>;
    

      'ContratoCerrado(uint256,uint8)': TypedContractEvent<ContratoCerradoEvent.InputTuple, ContratoCerradoEvent.OutputTuple, ContratoCerradoEvent.OutputObject>;
      ContratoCerrado: TypedContractEvent<ContratoCerradoEvent.InputTuple, ContratoCerradoEvent.OutputTuple, ContratoCerradoEvent.OutputObject>;
    

      'ContratoCreado(uint256,address,address)': TypedContractEvent<ContratoCreadoEvent.InputTuple, ContratoCreadoEvent.OutputTuple, ContratoCreadoEvent.OutputObject>;
      ContratoCreado: TypedContractEvent<ContratoCreadoEvent.InputTuple, ContratoCreadoEvent.OutputTuple, ContratoCreadoEvent.OutputObject>;
    

      'ContratoEditado(uint256,address)': TypedContractEvent<ContratoEditadoEvent.InputTuple, ContratoEditadoEvent.OutputTuple, ContratoEditadoEvent.OutputObject>;
      ContratoEditado: TypedContractEvent<ContratoEditadoEvent.InputTuple, ContratoEditadoEvent.OutputTuple, ContratoEditadoEvent.OutputObject>;
    

      'ContratoFirmado(uint256,address,string,string)': TypedContractEvent<ContratoFirmadoEvent.InputTuple, ContratoFirmadoEvent.OutputTuple, ContratoFirmadoEvent.OutputObject>;
      ContratoFirmado: TypedContractEvent<ContratoFirmadoEvent.InputTuple, ContratoFirmadoEvent.OutputTuple, ContratoFirmadoEvent.OutputObject>;
    

      'EntregaConfirmada(uint256,address)': TypedContractEvent<EntregaConfirmadaEvent.InputTuple, EntregaConfirmadaEvent.OutputTuple, EntregaConfirmadaEvent.OutputObject>;
      EntregaConfirmada: TypedContractEvent<EntregaConfirmadaEvent.InputTuple, EntregaConfirmadaEvent.OutputTuple, EntregaConfirmadaEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PrecioFijado(uint256,uint256)': TypedContractEvent<PrecioFijadoEvent.InputTuple, PrecioFijadoEvent.OutputTuple, PrecioFijadoEvent.OutputObject>;
      PrecioFijado: TypedContractEvent<PrecioFijadoEvent.InputTuple, PrecioFijadoEvent.OutputTuple, PrecioFijadoEvent.OutputObject>;
    

      'RelayerActualizado(address,address)': TypedContractEvent<RelayerActualizadoEvent.InputTuple, RelayerActualizadoEvent.OutputTuple, RelayerActualizadoEvent.OutputObject>;
      RelayerActualizado: TypedContractEvent<RelayerActualizadoEvent.InputTuple, RelayerActualizadoEvent.OutputTuple, RelayerActualizadoEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    
    };
  }