/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ContratoGranosSoja } from "./ContratoGranosSoja.ts";
export * as factories from "./factories/index.ts";
export { ContratoGranosSoja__factory } from "./factories/ContratoGranosSoja__factory.ts";
