/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ContratoGranosSoja } from "./ContratoGranosSoja";
export * as factories from "./factories";
export { ContratoGranosSoja__factory } from "./factories/ContratoGranosSoja__factory";
